windowrule {
    name = foot-style
    match:class = ^(foot)
    opacity = 1.0 0.85 1.0
}

windowrule {
    name = cava-bg
    match:class = foot-cava-bg
    float = true
    rounding = 0
    border_size = 0
    focus_on_activate = false
    opacity = 1.0 override 1.0 override
}
