exec-once = caelestia shell
exec-once = sleep 1 && hyprctl keyword input:touchpad:natural_scroll true
exec-once = sleep 1 && hyprctl keyword input:touchpad:tap-to-click true
exec-once = ~/.config/hypr/trackpad-fix.sh
exec-once = nm-applet --indicator 

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
        disable_while_typing = false
    }
}

device {
    name = your-touchpad-device-name-here
    natural_scroll = true
    tap-to-click = true
    drag_lock = true
    disable_while_typing = false
}

bind = $mainMod SHIFT, S, exec, grim -g "$(slupr)" - | wl-copy


