background {
    monitor =
    path = /home/yhvhan/Downloads/lockwallpaper.png
    blur_passes = 2
}

image {
    monitor =
    path = /home/yhvhan/.config/hypr/avatar.png
    size = 130
    rounding = -1
    border_size = 2
    border_color = rgb(222222)
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    fade_on_empty = false
    placeholder_text = <i>Input Password...</i>
    position = 0, -20
    halign = center
    valign = center
}
