-- Generated by HyprMod

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = true,
            passes = 1,
        },
        fullscreen_opacity = 1.0,
        inactive_opacity = 1.0,
        rounding = 10,
        rounding_power = 2.5,
        shadow = {
            enabled = false,
        },
    },
    general = {
        gaps_in = 0,
        gaps_out = 0,
    },
    gestures = {
        workspace_swipe_forever = true,
    },
    input = {
        accel_profile = "adaptive",
        natural_scroll = true,
        sensitivity = 0.05,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.03Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + SHIFT + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("hyprpicker -a"))
hl.unbind("SUPER + W")
hl.bind("SUPER + B", hl.dsp.exec_cmd("brave"))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.exec_cmd("/home/yhvhan/.local/share/kiro/kiro"))
hl.unbind("SUPER + ALT + R")
hl.bind("SUPER + ALT + R", hl.dsp.exec_cmd("obs -s"))
hl.unbind("SUPER + SHIFT + N")
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("joplin-desktop -s"))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("/opt/discord/discord"))
hl.unbind("SUPER + ALT + T")
hl.bind("SUPER + ALT + T", hl.dsp.exec_cmd("/opt/brave-bin/brave --profile-directory=Default --app-id=cifhbcnohmdccbgoicgdjpfamggdegmo"))
